# jwt:
#   secret: hG7t9yV@LmP!eXq2ZbF4#sWxUoN8rCdJkVpT6aMb


# spring:
#   security:
#     csrf:
#       enabled: false # إيقاف CSRF
#       disable: true

#   application:
#     name: apigateway

#   cloud:
#     gateway:
#       routes:
#         - id: auth-service
#           uri: http://localhost:8081
#           predicates:
#             - Path=/auth/**

#         - id: event-service
#           uri: http://localhost:8082
#           predicates:
#             - Path=/events/**
jwt:
  secret: hG7t9yV@LmP!eXq2ZbF4#sWxUoN8rCdJkVpT6aMb

spring:
  security:
    csrf:
      enabled: false  # CSRF disabled properly

  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**

        - id: event-service
          uri: http://localhost:8082/
          predicates:
            - Path=/events/**
