
# server:
#   port: 8080

# jwt:
#   secret: ThisIsMyVerySecretKeyForHS512ThatIsLongEnough123456

# spring:
#   application:
#     name: apigateway
#   main:
#     web-application-type: reactive

#   cloud:
#     gateway:
#       routes:
#         - id: AuthSer
#           uri: http://localhost:8081/
#           predicates:
#             - Path=/auth/**

server:
  port: 8080

spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: AuthSer
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**

        - id: EventSer
          uri: http://localhost:8082/
          predicates:
            - Path=/events/**
